// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Check API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/v1/account": {
            "get": {
                "description": "Never returns cloud credentials or tokens.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Get safe account metadata",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.AccountResponse"
                        }
                    }
                }
            }
        },
        "/v1/catalog": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get pricing catalog status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.CatalogResponse"
                        }
                    }
                }
            }
        },
        "/v1/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Get saved configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.Config"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Replace saved configuration",
                "parameters": [
                    {
                        "description": "Complete preferences",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.Config"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "configuration"
                ],
                "summary": "Reset saved configuration",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configuration"
                ],
                "summary": "Update saved configuration",
                "parameters": [
                    {
                        "description": "Partial preferences",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.ConfigPatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.Config"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    }
                }
            }
        },
        "/v1/estimates": {
            "post": {
                "description": "Calculates an estimate using the selected provider and pricing catalog.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estimates"
                ],
                "summary": "Create a cost estimate",
                "parameters": [
                    {
                        "description": "Estimate input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.EstimateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.EstimateResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    }
                }
            }
        },
        "/v1/providers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "List supported cloud providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apis.Provider"
                            }
                        }
                    }
                }
            }
        },
        "/v1/providers/{provider}/regions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "List provider regions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cloud provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apis.Region"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    }
                }
            }
        },
        "/v1/providers/{provider}/services": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discovery"
                ],
                "summary": "List provider services",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cloud provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/apis.Service"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/apis.Problem"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apis.AccountResponse": {
            "type": "object",
            "properties": {
                "account_reference": {
                    "type": "string"
                },
                "configured": {
                    "type": "boolean"
                },
                "credential_source": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "apis.CatalogResponse": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string",
                    "example": "embedded"
                },
                "status": {
                    "type": "string",
                    "example": "not_ready"
                },
                "version": {
                    "type": "string",
                    "example": "embedded-development"
                }
            }
        },
        "apis.Config": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "USD"
                },
                "default_provider": {
                    "type": "string",
                    "example": "aws"
                },
                "default_region": {
                    "type": "string",
                    "example": "ap-southeast-1"
                },
                "monthly_hours": {
                    "type": "number",
                    "example": 730
                },
                "pricing_mode": {
                    "type": "string",
                    "example": "offline"
                }
            }
        },
        "apis.ConfigPatch": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "default_provider": {
                    "type": "string"
                },
                "default_region": {
                    "type": "string"
                },
                "monthly_hours": {
                    "type": "number"
                },
                "pricing_mode": {
                    "type": "string"
                }
            }
        },
        "apis.EstimateRequest": {
            "type": "object",
            "properties": {
                "provider": {
                    "type": "string",
                    "example": "aws"
                },
                "provider_options": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "region": {
                    "type": "string",
                    "example": "ap-southeast-1"
                },
                "service": {
                    "type": "string",
                    "example": "ec2"
                },
                "usage": {
                    "$ref": "#/definitions/apis.Usage"
                }
            }
        },
        "apis.EstimateResult": {
            "type": "object",
            "properties": {
                "assumptions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "catalog_version": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "monthly_total": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        },
        "apis.Problem": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string",
                    "example": "hours must be greater than or equal to zero"
                },
                "instance": {
                    "type": "string",
                    "example": "/v1/estimates"
                },
                "request_id": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "status": {
                    "type": "integer",
                    "example": 400
                },
                "title": {
                    "type": "string",
                    "example": "Invalid request"
                },
                "type": {
                    "type": "string",
                    "example": "/problems/invalid-request"
                }
            }
        },
        "apis.Provider": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "aws"
                },
                "name": {
                    "type": "string",
                    "example": "Amazon Web Services"
                }
            }
        },
        "apis.Region": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ap-southeast-1"
                },
                "name": {
                    "type": "string",
                    "example": "Asia Pacific (Singapore)"
                }
            }
        },
        "apis.Service": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "ec2"
                },
                "name": {
                    "type": "string",
                    "example": "Amazon EC2"
                }
            }
        },
        "apis.Usage": {
            "type": "object",
            "properties": {
                "hours": {
                    "type": "number",
                    "example": 730
                },
                "instance": {
                    "type": "string",
                    "example": "t3.micro"
                },
                "storage_gb": {
                    "type": "number",
                    "example": 20
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "costGuard API",
	Description:      "Private API for estimating cloud costs across AWS, Azure, and GCP.\nEstimates are informational and depend on the selected pricing catalog.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
